#!/usr/bin/env bash

unset ROS_DISCOVERY_SERVER
unset ROS_SUPER_CLIENT
export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-30}"
export ROS_AUTOMATIC_DISCOVERY_RANGE="${ROS_AUTOMATIC_DISCOVERY_RANGE:-SUBNET}"

TB3_FASTDDS_PROFILE="${TB3_FASTDDS_PROFILE:-/workspace/ros2_ws/src/tb3_multimodal_interaction/config/fastdds_initial_peers.xml}"
if [ -f "$TB3_FASTDDS_PROFILE" ]; then
  export FASTRTPS_DEFAULT_PROFILES_FILE="$TB3_FASTDDS_PROFILE"
  export FASTDDS_DEFAULT_PROFILES_FILE="$TB3_FASTDDS_PROFILE"
fi
