ARG ROBOTIS_BASE_IMAGE
FROM ${ROBOTIS_BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        alsa-utils \
        v4l-utils \
        file \
    && rm -rf /var/lib/apt/lists/*
